### DISCUSSION TITLE
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY - DLRS, Heroku Connect, DupeCatcher, Composite Tree REST API

### DISCUSSION THREAD

**Discussion by nktnet1** [SFDO-Community/declarative-lookup-rollup-summaries#1527] [Q&A] [answered]
I've created a post in the Chatter Community Group here:
- https://trailhead.salesforce.com/trailblazer-community/feed/0D5KX00000Mawdg0AB

Although re-posting here for better formatting.

---

Currently, we have a custom web application that is used to accept form submissions from users. 

The app uses the sObject Tree (Composite Tree) REST API to create a parent record with children and grandchildren:
- https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_sobject_tree.htm

For example,
```typescript 
// conn object from jsforce 
await conn.requestPost( 
  `/services/data/v63.0/composite/tree/Event_Feedback__c`, 
  data, 
  { headers: { 'Sforce-Auto-Assign': 'FALSE' } }, 
); 
```

Our data schema looks like:   
``` 
Event ──────────────> Session ───────────> Session Speaker 
└─> Event Feedback ────> Session Feedback ────> Session Speaker Feedback 
```

Everything was working fine until we added a DLRS rollup field for the average rating on the Speaker object, based on its Speaker Feedback children records. We are using "Realtime" and "System". 

Now, when submitting the form, we run into the error: 

```json 
{ 
  "hasErrors": true, 
  "results": [ 
    { 
      "referenceId": "event_a00Mn00000RoxSEIAZ_speaker_a5NMn0000001EH3MAM", 
      "errors": [ 
        { 
          "statusCode": "CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY", 
          "message": "dlrs_Session_Speaker_FeedbackTrigger: execution of AfterInsert\n\ncaused by: System.DmlException: Update failed. First exception on row 0 with id a5NMn0000001EH3MAM; first error: CANNOT_EXECUTE_FLOW_TRIGGER, Can’t Save Record\nWe can't save this record because the “Update Herouku Connect” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: SFSSDupeCatcher.SSDupeCatcherContactTrigger: execution of BeforeUpdate\n\ncaused by: System.UnexpectedException: Salesforce System Error: 1018896272-315550 (1602293221) (1602293221)\n\n(System Code). You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943)k up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943): []\n\n(dlrs)\nTrigger.dlrs_Session_Speaker_FeedbackTrigger: line 7, column 1", 
          "fields": [] 
        } 
      ] 
    }, 
    { 
      "referenceId": "event_a00Mn00000RoxSEIAZ_speaker_a5NMn0000001EIfMAM", 
      "errors": [ 
        { 
          "statusCode": "CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY", 
          "message": "dlrs_Session_Speaker_FeedbackTrigger: execution of AfterInsert\n\ncaused by: System.DmlException: Update failed. First exception on row 0 with id a5NMn0000001EH3MAM; first error: CANNOT_EXECUTE_FLOW_TRIGGER, Can’t Save Record\nWe can't save this record because the “Update Herouku Connect” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: SFSSDupeCatcher.SSDupeCatcherContactTrigger: execution of BeforeUpdate\n\ncaused by: System.UnexpectedException: Salesforce System Error: 1018896272-315550 (1602293221) (1602293221)\n\n(System Code). You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943)k up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943): []\n\n(dlrs)\nTrigger.dlrs_Session_Speaker_FeedbackTrigger: line 7, column 1", 
          "fields": [] 
        } 
      ] 
    } 
  ] 
} 
```

<details close>
<summary>Click to view a more readable error body in YAML</summary>

```yaml
---
hasErrors: true
results:
- referenceId: event_a00Mn00000RoxSEIAZ_speaker_a5NMn0000001EH3MAM
  errors:
  - statusCode: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
    message: |-
      dlrs_Session_Speaker_FeedbackTrigger: execution of AfterInsert

      caused by: System.DmlException: Update failed. First exception on row 0 with id a5NMn0000001EH3MAM; first error: CANNOT_EXECUTE_FLOW_TRIGGER, Can’t Save Record
      We can't save this record because the “Update Herouku Connect” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: SFSSDupeCatcher.SSDupeCatcherContactTrigger: execution of BeforeUpdate

      caused by: System.UnexpectedException: Salesforce System Error: 1018896272-315550 (1602293221) (1602293221)

      (System Code). You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943)k up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943): []

      (dlrs)
      Trigger.dlrs_Session_Speaker_FeedbackTrigger: line 7, column 1
    fields: []
- referenceId: event_a00Mn00000RoxSEIAZ_speaker_a5NMn0000001EIfMAM
  errors:
  - statusCode: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY
    message: |-
      dlrs_Session_Speaker_FeedbackTrigger: execution of AfterInsert

      caused by: System.DmlException: Update failed. First exception on row 0 with id a5NMn0000001EH3MAM; first error: CANNOT_EXECUTE_FLOW_TRIGGER, Can’t Save Record
      We can't save this record because the “Update Herouku Connect” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: SFSSDupeCatcher.SSDupeCatcherContactTrigger: execution of BeforeUpdate

      caused by: System.UnexpectedException: Salesforce System Error: 1018896272-315550 (1602293221) (1602293221)

      (System Code). You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943)k up ExceptionCode values in the SOAP API Developer Guide. Error ID: 1018896272-315554 (-128950943): []

      (dlrs)
      Trigger.dlrs_Session_Speaker_FeedbackTrigger: line 7, column 1
    fields: []
```

</details>

The Event (+ Event Feedback) and Session (+ Session Feedback) also uses DLRS to compute the average, but there is no error for these when submitting. 

There is also no errors when manually running the "Recalculate now" feature from DLRS - only when it is being used as a realtime trigger. 

Looking at the error message, there seems to be a conflict with one (or both) of
- Heroku Connect
- DupeCatcher

 
Do you have any idea how this can be debugged/resolved? For the time being, we have simply disabled the average rating trigger for our Session Speaker object.

Thank you!
